"""remove teacher user and update attendance

Revision ID: 011c90cb75f8
Revises: 439298b4069b
Create Date: 2026-07-18 22:36:47.711031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "011c90cb75f8"
down_revision: Union[str, Sequence[str], None] = "439298b4069b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lessons", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f("ix_lessons_starts_at"), table_name="lessons")
    op.add_column("teachers", sa.Column("first_name", sa.String(length=100), nullable=False))
    op.add_column("teachers", sa.Column("last_name", sa.String(length=100), nullable=False))
    op.add_column("teachers", sa.Column("phone", sa.String(length=12), nullable=True))
    op.add_column("teachers", sa.Column("email", sa.String(length=255), nullable=True))
    op.drop_index(op.f("ix_teachers_user_id"), table_name="teachers")
    op.drop_constraint(op.f("teachers_user_id_fkey"), "teachers", type_="foreignkey")
    op.drop_column("teachers", "user_id")
    op.drop_index(op.f("ix_users_branch_id"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_branch_id"), "users", ["branch_id"], unique=False)
    op.add_column("teachers", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("teachers_user_id_fkey"), "teachers", "users", ["user_id"], ["id"], ondelete="RESTRICT")
    op.create_index(op.f("ix_teachers_user_id"), "teachers", ["user_id"], unique=True)
    op.drop_column("teachers", "email")
    op.drop_column("teachers", "phone")
    op.drop_column("teachers", "last_name")
    op.drop_column("teachers", "first_name")
    op.create_index(op.f("ix_lessons_starts_at"), "lessons", ["starts_at"], unique=False)
    op.drop_column("lessons", "completed_at")
    # ### end Alembic commands ###
