"""create schedule and lessons

Revision ID: 32345db66137
Revises: c43f3dc502be
Create Date: 2026-07-16 20:21:02.762556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "32345db66137"
down_revision: Union[str, Sequence[str], None] = "c43f3dc502be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_slots",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("hall_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("start_time < end_time", name="ck_schedule_slots_time_range"),
        sa.CheckConstraint("weekday >= 0 AND weekday <= 6", name="ck_schedule_slots_weekday_range"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["hall_id"], ["halls.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "weekday", "start_time", name="uq_schedule_slots_group_weekday_start"),
    )
    op.create_index(op.f("ix_schedule_slots_group_id"), "schedule_slots", ["group_id"], unique=False)
    op.create_index(op.f("ix_schedule_slots_hall_id"), "schedule_slots", ["hall_id"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("schedule_slot_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("hall_id", sa.Integer(), nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("planned", "completed", "cancelled", name="lesson_status"),
            server_default="planned",
            nullable=False,
        ),
        sa.Column("cancellation_reason", sa.String(length=500), nullable=True),
        sa.Column("cancelled_by_studio", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("cancelled_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("starts_at < ends_at", name="ck_lessons_datetime_range"),
        sa.ForeignKeyConstraint(["cancelled_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["hall_id"], ["halls.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["schedule_slot_id"], ["schedule_slots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["teacher_id"], ["teachers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_slot_id", "starts_at", name="uq_lessons_schedule_slot_starts_at"),
    )
    op.create_index(op.f("ix_lessons_group_id"), "lessons", ["group_id"], unique=False)
    op.create_index(op.f("ix_lessons_hall_id"), "lessons", ["hall_id"], unique=False)
    op.create_index(op.f("ix_lessons_schedule_slot_id"), "lessons", ["schedule_slot_id"], unique=False)
    op.create_index(op.f("ix_lessons_starts_at"), "lessons", ["starts_at"], unique=False)
    op.create_index(op.f("ix_lessons_teacher_id"), "lessons", ["teacher_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lessons_teacher_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_starts_at"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_schedule_slot_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_hall_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_group_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_schedule_slots_hall_id"), table_name="schedule_slots")
    op.drop_index(op.f("ix_schedule_slots_group_id"), table_name="schedule_slots")
    op.drop_table("schedule_slots")
    # ### end Alembic commands ###
